[package]
name = "ecs_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
macro_utils = { path = "../macro_utils", version = "0.1.0" }

syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
