[package]
name = "arara"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal
arara_internal = { path = "crates/arara_internal", version = "0.1.0" }
# external
glium = "*"
image = "*"
cgmath = "*"
rand = "*"
