[package]
name = "arara"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal
arara_camera = { path = "crates/arara_camera", version = "0.1.0" }
arara_geometry = { path = "crates/arara_geometry", version = "0.1.0" }
arara_shaders = { path = "crates/arara_shaders", version = "0.1.0" }
arara_transform = { path = "crates/arara_transform", version = "0.1.0" }
# external
glium = "*"
image = "*"
cgmath = "*"
rand = "*"
