use arara_input::{
    keyboard::{KeyCode, KeyboardInput},
    mouse::MouseButton,
    ElementState,
};
use glium::glutin::event;

pub fn convert_keyboard_input(keyboard_input: &event::KeyboardInput) -> KeyboardInput {
    KeyboardInput {
        scan_code: keyboard_input.scancode,
        state: convert_element_state(keyboard_input.state),
        key_code: keyboard_input.virtual_keycode.map(convert_virtual_key_code),
    }
}

pub fn convert_element_state(element_state: event::ElementState) -> ElementState {
    match element_state {
        event::ElementState::Pressed => ElementState::Pressed,
        event::ElementState::Released => ElementState::Released,
    }
}

pub fn convert_mouse_button(mouse_button: event::MouseButton) -> MouseButton {
    match mouse_button {
        event::MouseButton::Left => MouseButton::Left,
        event::MouseButton::Right => MouseButton::Right,
        event::MouseButton::Middle => MouseButton::Middle,
        event::MouseButton::Other(val) => MouseButton::Other(val),
    }
}

pub fn convert_virtual_key_code(virtual_key_code: event::VirtualKeyCode) -> KeyCode {
    match virtual_key_code {
        event::VirtualKeyCode::Key1 => KeyCode::Key1,
        event::VirtualKeyCode::Key2 => KeyCode::Key2,
        event::VirtualKeyCode::Key3 => KeyCode::Key3,
        event::VirtualKeyCode::Key4 => KeyCode::Key4,
        event::VirtualKeyCode::Key5 => KeyCode::Key5,
        event::VirtualKeyCode::Key6 => KeyCode::Key6,
        event::VirtualKeyCode::Key7 => KeyCode::Key7,
        event::VirtualKeyCode::Key8 => KeyCode::Key8,
        event::VirtualKeyCode::Key9 => KeyCode::Key9,
        event::VirtualKeyCode::Key0 => KeyCode::Key0,
        event::VirtualKeyCode::A => KeyCode::A,
        event::VirtualKeyCode::B => KeyCode::B,
        event::VirtualKeyCode::C => KeyCode::C,
        event::VirtualKeyCode::D => KeyCode::D,
        event::VirtualKeyCode::E => KeyCode::E,
        event::VirtualKeyCode::F => KeyCode::F,
        event::VirtualKeyCode::G => KeyCode::G,
        event::VirtualKeyCode::H => KeyCode::H,
        event::VirtualKeyCode::I => KeyCode::I,
        event::VirtualKeyCode::J => KeyCode::J,
        event::VirtualKeyCode::K => KeyCode::K,
        event::VirtualKeyCode::L => KeyCode::L,
        event::VirtualKeyCode::M => KeyCode::M,
        event::VirtualKeyCode::N => KeyCode::N,
        event::VirtualKeyCode::O => KeyCode::O,
        event::VirtualKeyCode::P => KeyCode::P,
        event::VirtualKeyCode::Q => KeyCode::Q,
        event::VirtualKeyCode::R => KeyCode::R,
        event::VirtualKeyCode::S => KeyCode::S,
        event::VirtualKeyCode::T => KeyCode::T,
        event::VirtualKeyCode::U => KeyCode::U,
        event::VirtualKeyCode::V => KeyCode::V,
        event::VirtualKeyCode::W => KeyCode::W,
        event::VirtualKeyCode::X => KeyCode::X,
        event::VirtualKeyCode::Y => KeyCode::Y,
        event::VirtualKeyCode::Z => KeyCode::Z,
        event::VirtualKeyCode::Escape => KeyCode::Escape,
        event::VirtualKeyCode::F1 => KeyCode::F1,
        event::VirtualKeyCode::F2 => KeyCode::F2,
        event::VirtualKeyCode::F3 => KeyCode::F3,
        event::VirtualKeyCode::F4 => KeyCode::F4,
        event::VirtualKeyCode::F5 => KeyCode::F5,
        event::VirtualKeyCode::F6 => KeyCode::F6,
        event::VirtualKeyCode::F7 => KeyCode::F7,
        event::VirtualKeyCode::F8 => KeyCode::F8,
        event::VirtualKeyCode::F9 => KeyCode::F9,
        event::VirtualKeyCode::F10 => KeyCode::F10,
        event::VirtualKeyCode::F11 => KeyCode::F11,
        event::VirtualKeyCode::F12 => KeyCode::F12,
        event::VirtualKeyCode::F13 => KeyCode::F13,
        event::VirtualKeyCode::F14 => KeyCode::F14,
        event::VirtualKeyCode::F15 => KeyCode::F15,
        event::VirtualKeyCode::F16 => KeyCode::F16,
        event::VirtualKeyCode::F17 => KeyCode::F17,
        event::VirtualKeyCode::F18 => KeyCode::F18,
        event::VirtualKeyCode::F19 => KeyCode::F19,
        event::VirtualKeyCode::F20 => KeyCode::F20,
        event::VirtualKeyCode::F21 => KeyCode::F21,
        event::VirtualKeyCode::F22 => KeyCode::F22,
        event::VirtualKeyCode::F23 => KeyCode::F23,
        event::VirtualKeyCode::F24 => KeyCode::F24,
        event::VirtualKeyCode::Snapshot => KeyCode::Snapshot,
        event::VirtualKeyCode::Scroll => KeyCode::Scroll,
        event::VirtualKeyCode::Pause => KeyCode::Pause,
        event::VirtualKeyCode::Insert => KeyCode::Insert,
        event::VirtualKeyCode::Home => KeyCode::Home,
        event::VirtualKeyCode::Delete => KeyCode::Delete,
        event::VirtualKeyCode::End => KeyCode::End,
        event::VirtualKeyCode::PageDown => KeyCode::PageDown,
        event::VirtualKeyCode::PageUp => KeyCode::PageUp,
        event::VirtualKeyCode::Left => KeyCode::Left,
        event::VirtualKeyCode::Up => KeyCode::Up,
        event::VirtualKeyCode::Right => KeyCode::Right,
        event::VirtualKeyCode::Down => KeyCode::Down,
        event::VirtualKeyCode::Back => KeyCode::Back,
        event::VirtualKeyCode::Return => KeyCode::Return,
        event::VirtualKeyCode::Space => KeyCode::Space,
        event::VirtualKeyCode::Compose => KeyCode::Compose,
        event::VirtualKeyCode::Caret => KeyCode::Caret,
        event::VirtualKeyCode::Numlock => KeyCode::Numlock,
        event::VirtualKeyCode::Numpad0 => KeyCode::Numpad0,
        event::VirtualKeyCode::Numpad1 => KeyCode::Numpad1,
        event::VirtualKeyCode::Numpad2 => KeyCode::Numpad2,
        event::VirtualKeyCode::Numpad3 => KeyCode::Numpad3,
        event::VirtualKeyCode::Numpad4 => KeyCode::Numpad4,
        event::VirtualKeyCode::Numpad5 => KeyCode::Numpad5,
        event::VirtualKeyCode::Numpad6 => KeyCode::Numpad6,
        event::VirtualKeyCode::Numpad7 => KeyCode::Numpad7,
        event::VirtualKeyCode::Numpad8 => KeyCode::Numpad8,
        event::VirtualKeyCode::Numpad9 => KeyCode::Numpad9,
        event::VirtualKeyCode::AbntC1 => KeyCode::AbntC1,
        event::VirtualKeyCode::AbntC2 => KeyCode::AbntC2,
        event::VirtualKeyCode::NumpadAdd => KeyCode::NumpadAdd,
        event::VirtualKeyCode::Apostrophe => KeyCode::Apostrophe,
        event::VirtualKeyCode::Apps => KeyCode::Apps,
        event::VirtualKeyCode::Asterisk => KeyCode::Asterisk,
        event::VirtualKeyCode::Plus => KeyCode::Plus,
        event::VirtualKeyCode::At => KeyCode::At,
        event::VirtualKeyCode::Ax => KeyCode::Ax,
        event::VirtualKeyCode::Backslash => KeyCode::Backslash,
        event::VirtualKeyCode::Calculator => KeyCode::Calculator,
        event::VirtualKeyCode::Capital => KeyCode::Capital,
        event::VirtualKeyCode::Colon => KeyCode::Colon,
        event::VirtualKeyCode::Comma => KeyCode::Comma,
        event::VirtualKeyCode::Convert => KeyCode::Convert,
        event::VirtualKeyCode::NumpadDecimal => KeyCode::NumpadDecimal,
        event::VirtualKeyCode::NumpadDivide => KeyCode::NumpadDivide,
        event::VirtualKeyCode::Equals => KeyCode::Equals,
        event::VirtualKeyCode::Grave => KeyCode::Grave,
        event::VirtualKeyCode::Kana => KeyCode::Kana,
        event::VirtualKeyCode::Kanji => KeyCode::Kanji,
        event::VirtualKeyCode::LAlt => KeyCode::LAlt,
        event::VirtualKeyCode::LBracket => KeyCode::LBracket,
        event::VirtualKeyCode::LControl => KeyCode::LControl,
        event::VirtualKeyCode::LShift => KeyCode::LShift,
        event::VirtualKeyCode::LWin => KeyCode::LWin,
        event::VirtualKeyCode::Mail => KeyCode::Mail,
        event::VirtualKeyCode::MediaSelect => KeyCode::MediaSelect,
        event::VirtualKeyCode::MediaStop => KeyCode::MediaStop,
        event::VirtualKeyCode::Minus => KeyCode::Minus,
        event::VirtualKeyCode::NumpadMultiply => KeyCode::NumpadMultiply,
        event::VirtualKeyCode::Mute => KeyCode::Mute,
        event::VirtualKeyCode::MyComputer => KeyCode::MyComputer,
        event::VirtualKeyCode::NavigateForward => KeyCode::NavigateForward,
        event::VirtualKeyCode::NavigateBackward => KeyCode::NavigateBackward,
        event::VirtualKeyCode::NextTrack => KeyCode::NextTrack,
        event::VirtualKeyCode::NoConvert => KeyCode::NoConvert,
        event::VirtualKeyCode::NumpadComma => KeyCode::NumpadComma,
        event::VirtualKeyCode::NumpadEnter => KeyCode::NumpadEnter,
        event::VirtualKeyCode::NumpadEquals => KeyCode::NumpadEquals,
        event::VirtualKeyCode::OEM102 => KeyCode::Oem102,
        event::VirtualKeyCode::Period => KeyCode::Period,
        event::VirtualKeyCode::PlayPause => KeyCode::PlayPause,
        event::VirtualKeyCode::Power => KeyCode::Power,
        event::VirtualKeyCode::PrevTrack => KeyCode::PrevTrack,
        event::VirtualKeyCode::RAlt => KeyCode::RAlt,
        event::VirtualKeyCode::RBracket => KeyCode::RBracket,
        event::VirtualKeyCode::RControl => KeyCode::RControl,
        event::VirtualKeyCode::RShift => KeyCode::RShift,
        event::VirtualKeyCode::RWin => KeyCode::RWin,
        event::VirtualKeyCode::Semicolon => KeyCode::Semicolon,
        event::VirtualKeyCode::Slash => KeyCode::Slash,
        event::VirtualKeyCode::Sleep => KeyCode::Sleep,
        event::VirtualKeyCode::Stop => KeyCode::Stop,
        event::VirtualKeyCode::NumpadSubtract => KeyCode::NumpadSubtract,
        event::VirtualKeyCode::Sysrq => KeyCode::Sysrq,
        event::VirtualKeyCode::Tab => KeyCode::Tab,
        event::VirtualKeyCode::Underline => KeyCode::Underline,
        event::VirtualKeyCode::Unlabeled => KeyCode::Unlabeled,
        event::VirtualKeyCode::VolumeDown => KeyCode::VolumeDown,
        event::VirtualKeyCode::VolumeUp => KeyCode::VolumeUp,
        event::VirtualKeyCode::Wake => KeyCode::Wake,
        event::VirtualKeyCode::WebBack => KeyCode::WebBack,
        event::VirtualKeyCode::WebFavorites => KeyCode::WebFavorites,
        event::VirtualKeyCode::WebForward => KeyCode::WebForward,
        event::VirtualKeyCode::WebHome => KeyCode::WebHome,
        event::VirtualKeyCode::WebRefresh => KeyCode::WebRefresh,
        event::VirtualKeyCode::WebSearch => KeyCode::WebSearch,
        event::VirtualKeyCode::WebStop => KeyCode::WebStop,
        event::VirtualKeyCode::Yen => KeyCode::Yen,
        event::VirtualKeyCode::Copy => KeyCode::Copy,
        event::VirtualKeyCode::Paste => KeyCode::Paste,
        event::VirtualKeyCode::Cut => KeyCode::Cut,
    }
}
