[package]
name = "arara_app"
version = "0.1.0"
edition = "2021"

[features]
trace = []

[dependencies]
# internal
arara_utils = { path = "../arara_utils", version = "0.1.0" }
arara_ecs = { path = "../arara_ecs", version = "0.1.0" }
# external
glium = "0.31.0"
cgmath = "0.18.0"